### ISSUE TITLE
Canvas Multiple Character Drawing

### ISSUE THREAD

**Issue by xeoh** [JeOhLee/MyLittleFont#48]
Current canvas support drawing only one character(```Locater```). We need to extend ```FontDrawerView``` to support multiple characters.

#### TODO
- [x] Make ```FontDrawerView``` draw multiple ```Locator```s.
- [x] Define space between letter(자간)
- [x] Make ```FontMakerFragment``` gets text input from user.
- [x] Make uncompleted characters drawable. (```ㄱ```)
- [x] Handling unsupported characters. (i.e. Special Characters)
- [x] Control size of drawn fonts.
